export const MAIN_IMAGE_LOADING = 'MAIN_IMAGE_LOADING';
export const MAIN_IMAGE_LOADED = 'MAIN_IMAGE_LOADED';
export const MAIN_IMAGE_SET = 'MAIN_IMAGE_SET';
export const MAIN_IMAGE_RESET_STATUSES = 'MAIN_IMAGE_RESET_STATUSES';
export const MAIN_IMAGE_DROP = 'MAIN_IMAGE_DROP'

export const MAIN_IMAGES_LOADING = 'MAIN_IMAGES_LOADING';
export const MAIN_IMAGES_LOADED = 'MAIN_IMAGES_LOADED';
export const MAIN_IMAGES_SET = 'MAIN_IMAGES_SET';
export const MAIN_IMAGES_RESET_STATUSES = 'MAIN_IMAGES_RESET_STATUSES';
export const MAIN_IMAGES_DROP = 'MAIN_IMAGES_DROP'