export const NATION_LOADING = 'NATION_LOADING';
export const NATION_LOADED = 'NATION_LOADED';
export const NATION_SET = 'NATION_SET';
export const NATION_DROP = 'NATION_DROP';
export const NATION_RESET_STATUSES = 'NATION_RESET_STATUSES';